spring:
  application:
    name: agenda
  port: 8080

  data:
    mongodb:
      host: localhost
      port: 27017
      database: agenda_db
      authentication-database: admin
      username: adminuser
      password: password

      uuid-representation: standard
springdoc:
  api-docs:
    path: /api-docs